
services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./projects:/root  # Mount the host project directory to /root in the container
    ports:
      - "3306:3306"
      - "8080:8080"
    stdin_open: true
    tty: true

